### ISSUE TITLE
Initial Review

### ISSUE THREAD

**Issue by hansmosh** [nio-blocks/mysql#1]
- [x] Add a README - most blocks have one. Examples: https://github.com/nio-blocks/socketio https://github.com/nio-blocks/util
- [x] Replace print statement with self._logger.debug
- [x] Add a little extra logging info. Example: debug message for number of signals inserted. (EDIT: I see that the driver is handling a lot of the logging)
- [x] What happens when add_items fails? Log an error for signals that fail to get inserted.
- [x] Rename file - We tend to label the files as the block name and then the work 'block' at the end. This would be 'mysql_db_insert_block'. You could probably remove the 'DB' from the block and file name: MySQLInsert. mysql_insert_block.py.
- [x] Why does the block have DependsOn Communication?
- [x] Instead of using the signal class to define the table and a tables_prefix, the block should just store all signals to the same table. If it's not too complicated, maybe even make the table property an ExpressionProperty.

**Comment by mattdodge** [comment]
A few more:

- Should use a relative import here: https://github.com/nio-blocks/mysql/blob/master/driver/tests/test_mysql.py#L2
- Add a .gitignore - shouldn't have __pycache__ and all that. Most block repos have an example one you can probably use

**Comment by mattdodge** [comment]
Looks like these have all been addressed, maybe one left? @hansmosh what do you think?

**Comment by mattdodge** [comment]
All done, closing
